[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
sleep = "AnEoEjuCrNR7ytBk3hLwrGCQHmCPEo2Dfr4pbsUGpDyH"

[programs.Localnet]
sleep = "AnEoEjuCrNR7ytBk3hLwrGCQHmCPEo2Dfr4pbsUGpDyH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false
